project:
  type: website
  output-dir: docs
website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "The Data Science Blog"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/eric-yang2/
      - icon: github
        href: https://github.com/EricYangg

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



